import type { ActionConfig } from "@/lib/rules/types";

export const NATURAL_ACTIONS: ActionConfig[] = [
  {
    id: "t2",
    tier: "T2",
    title: "Refine Raw → Fine",
    subtitle: "Convert raw essence into fine essence with escalating risk options.",
    gradient: { from: "from-emerald-500", to: "to-emerald-700" },
    risks: [
      {
        id: "low",
        label: "Low risk",
        description: "DC 5 • 3 Raw → 1 Fine • Salvage: DC 8 → +2 Raw",
        baseDc: 5,
        inputs: { raw: 3 },
        outputs: { fine: 1 },
        salvage: { dc: 8, returns: { raw: 2 } },
        timeMinutes: 30,
      },
      {
        id: "standard",
        label: "Standard risk",
        description: "DC 12 • 2 Raw → 1 Fine • Salvage: DC 12 → +1 Raw",
        baseDc: 12,
        inputs: { raw: 2 },
        outputs: { fine: 1 },
        salvage: { dc: 12, returns: { raw: 1 } },
        timeMinutes: 60,
      },
      {
        id: "high",
        label: "High risk",
        description: "DC 20 • 1 Raw → 1 Fine • No salvage",
        baseDc: 20,
        inputs: { raw: 1 },
        outputs: { fine: 1 },
        timeMinutes: 120,
      },
    ],
  },
  {
    id: "t3",
    tier: "T3",
    title: "Infuse Fine + RawAE → Fused",
    subtitle: "Blend refined essence with arcane catalysts to forge fused essence.",
    gradient: { from: "from-sky-500", to: "to-sky-700" },
    risks: [
      {
        id: "standard",
        label: "Standard",
        description: "DC 12 • 2 Fine + 2 RawAE → 1 Fused • Salvage: DC 10 → +2 Fine",
        baseDc: 12,
        inputs: { fine: 2, rawAE: 2 },
        outputs: { fused: 1 },
        salvage: { dc: 10, returns: { fine: 2 } },
        timeMinutes: 30,
      },
    ],
  },
  {
    id: "t4",
    tier: "T4",
    title: "Refine Fused → Superior",
    subtitle: "Push fused essence beyond its limits; spend RawAE to ease the DC.",
    gradient: { from: "from-violet-500", to: "to-violet-700" },
    optionalCost: {
      resource: "rawAE",
      label: "Raw Arcane Essence per attempt (–4 DC each)",
      perUnitDcReduction: 4,
      minDc: 5,
    },
    risks: [
      {
        id: "low",
        label: "Low risk",
        description: "Base DC 12 • 3 Fused → 1 Superior • Salvage: DC 10 → +5 Fine",
        baseDc: 12,
        inputs: { fused: 3 },
        outputs: { superior: 1 },
        salvage: { dc: 10, returns: { fine: 5 } },
        timeMinutes: 60,
      },
      {
        id: "standard",
        label: "Standard risk",
        description: "Base DC 18 • 2 Fused → 1 Superior • Salvage: DC 14 → +3 Fine",
        baseDc: 18,
        inputs: { fused: 2 },
        outputs: { superior: 1 },
        salvage: { dc: 14, returns: { fine: 3 } },
        timeMinutes: 120,
      },
      {
        id: "high",
        label: "High risk",
        description: "Base DC 34 • 1 Fused → 1 Superior • Salvage: DC 18 → +1 Fine",
        baseDc: 34,
        inputs: { fused: 1 },
        outputs: { superior: 1 },
        salvage: { dc: 18, returns: { fine: 1 } },
        timeMinutes: 480,
      },
    ],
  },
  {
    id: "t5",
    tier: "T5",
    title: "Refine Superior → Supreme",
    subtitle: "Finish the cycle by elevating superior essence into its supreme form.",
    gradient: { from: "from-amber-500", to: "to-amber-700" },
    risks: [
      {
        id: "standard",
        label: "Standard risk",
        description: "DC 12 • 3 Superior → 1 Supreme • Salvage: DC 10 → +2 Superior",
        baseDc: 12,
        inputs: { superior: 3 },
        outputs: { supreme: 1 },
        salvage: { dc: 10, returns: { superior: 2 } },
        timeMinutes: 60,
      },
      {
        id: "high",
        label: "High risk",
        description: "DC 18 • 2 Superior → 1 Supreme • Salvage: DC 15 → +1 Superior",
        baseDc: 18,
        inputs: { superior: 2 },
        outputs: { supreme: 1 },
        salvage: { dc: 15, returns: { superior: 1 } },
        timeMinutes: 120,
      },
    ],
  },
];
